### PR TITLE
Restart hubot after successfull build

### PR DESCRIPTION
**Pull request by pjaspers**
Since the `bin/hubot` script calls `npm install`, restarting it should
update its dependencies and therefore should fetch this repo again as
well, it should Just Work and its no longer needed to take further
action to add the changes from this repo to hubot.

Steps I took to get to this stage:

`travis encrypt APP_ID_OR_NAME=<hubot-on-heroku> --add env.global`

`travis encrypt HEROKU_API_KEY=<hubot-api-key --add env.global`

(You can get the heroku api key by issueing: `heroku auth:token`)

This makes these variables available to the `after_success` hook, so we
can securely® use them in our curl script, which calls the Heroku API
and restarts meechum.

What this means is that adding a gif is now even easier, just make a
pull request that passes the tests and once someone merges it, it will
automagically be available in hubot.

### CODE REVIEW

**Comment by pjaspers** [comment]
I've been doing this all wrong. If I just make it a script I a can make it a custom deployment script and Travis will do all the checks for us.

**Comment by To1ne** [comment]
I am not an expert, but isn't there [something](http://docs.travis-ci.com/user/deployment/script/) missing?:

``` yaml
  on:
    branch: master
```

**Comment by pjaspers** [comment]
I think that's the default

**Comment by To1ne** [comment]
I think you are [right](https://github.com/travis-ci/travis-build/blob/a76974130b5d4ed97ff01c950afb2fea8115a0a4/lib/travis/build/addons/deploy/script.rb#L81-L85).

**Pull request merged**
